export const APP_CONFIG: any = {
  DEFAULT_DATE_FORMAT: 'MMM d, y, h:mm:ss a',
  MAX_PAGE_VALUE_COUNT: 10,
  PAGE_OFFSET: 0,
  PAGE_SIZE_OPTIONS: [5, 10, 20, 50, 100],
  DEFAULT_VALUE_STATUS: { true: 'Active', false: 'Inactive' },
  DEFAULT_USER_TYPE: { '1': 'Admin', '0': 'User' },
  DEFAULT_MANUAL_OPERATIONS_ACTION: { true: 'Enabled', false: 'Disabled' },

  FIELDS: {
    LOGIN: {
      username: {
        name: 'username',
        type: 'email',
        label: 'User Name',
        placeholder: 'Enter Username',
        errorMessage: 'Username not provided!',
        required: true,
      },
      password: {
        name: 'password',
        type: 'password',
        label: 'Password',
        placeholder: 'Enter password',
        errorMessage: 'Password not provided or invalid!',
        required: true,
      },
    },
    FORGET_PASSWORD: {
      email: {
        show: 'true',
        name: 'email',
        type: 'email',
        label: 'Email',
        placeholder: 'Enter email',
        errorMessage: 'Entered email',
        required: true,
      },
    },
    RESET_PASSWORD: {
      new_password: {
        name: 'new_password',
        type: 'password',
        label: 'New Password',
        placeholder: 'Enter password',
        errorMessage: 'Password not provided or invalid!',
        required: true,
      },
      repeat_password: {
        name: 'repeat_password',
        type: 'password',
        label: 'Repeat New Password',
        placeholder: 'Enter password',
        errorMessage: 'Password not provided or invalid!',
        required: true,
      },
    },
    WEB_MONITOR: {
      WEBSITES : {
        ADD_EDIT_WEBSITES : [
          // {
          //   fieldName: 'name',
          //   label: 'Name',
          //   type: 'input',
          //   placeholder: 'Enter a friendly name/alias',
          //   required: false,
          // },
          {
            fieldName: 'website',
            label: 'Website/URL ',
            type: 'input',
            placeholder: 'E.g. google.com',
            required: true,
          },
          // {
          //   fieldName: 'interval',
          //   label: 'Interval',
          //   type: 'select',
          //   required: true,
          //   optios :[
          //     { value: 1, viewValue: '1 minute' },
          //     { value: 5, viewValue: '5 minutes' },
          //     { value: 10, viewValue: '10 minutes' },
          //     { value: 30, viewValue: '30 minutes' },
          //     { value: 60, viewValue: '1 hour' },
          //   ]
          // },
          {
            fieldName: 'ping',
            label: 'Ping',
            type: 'object',
            choose :[{
              fieldName : 'enabled',
              type : 'checkbox'
            }]
            // placeholder: 'Enter a friendly name/alias',
            // required: true,
          },
          {
            fieldName: 'ssl',
            label: 'SSL',
            type: 'checkbox',
            // placeholder: 'Enter a friendly name/alias',
            // required: true,
          },
          {
            fieldName: 'spellCheck',
            label: 'Spell Check',
            type: 'checkbox',
            // placeholder: 'Enter a friendly name/alias',
            // required: true,
          },
        ],
        LIST_VIEW: {
          HEADER_LIST: [
            'status',
            'ID',
            'name',
            'website',
            'interval',
            'createdAt',
            'createdBy',
            'enable',
            'options',
          ],
          HEADER_LABEL: {
            status: 'Status',
            ID:'ID',
            name: 'Name',
            website: 'Website',
            interval: 'Interval',
            createdAt: 'Created At',
            createdBy: 'Created By',
            enable: 'Enable/Disable',
            options: 'Operation',
          },
          ACTION_OPTIONS: ['edit', 'view', 'delete', 'alert'],
        },
      },
      PING: {
        ADD_EDIT_PING: [
          {
            fieldName: 'name',
            label: 'Name',
            type: 'input',
            placeholder: 'Enter a friendly name/alias',
            required: true,
          },
          {
            fieldName: 'host',
            label: 'IP/Domain',
            type: 'input',
            placeholder: 'e.g. google.com or 142.250.194.142',
            required: true,
            pattern: '^((([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6})|((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(\\/.*)?$',
          },
          {
            fieldName: 'interval',
            label: 'Interval',
            type: 'select',
            required: true,
            options: [
              { value: 1, viewValue: '1 minute' },
              { value: 5, viewValue: '5 minutes' },
              { value: 10, viewValue: '10 minutes' },
              { value: 30, viewValue: '30 minutes' },
              { value: 60, viewValue: '1 hour' },
            ],
          },
        ],
        LIST_VIEW: {
          HEADER_LIST: [
            'status',
            'counter',
            'name',
            'url',
            'interval',
            'createdAt',
            'createdBy',
            'latestRecord',
            'enable',
            'options',
          ],
          HEADER_LABEL: {
            counter: 'ID',
            name: 'Name',
            url: 'Url',
            interval: 'Interval',
            createdAt: 'Created At',
            createdBy: 'Created By',
            latestRecord: 'Latest Value(ping Time)',
            status: 'Status',
            enable: 'Enable/Disable',
            options: 'Operation',
          },
          ACTION_OPTIONS: ['edit', 'view', 'delete', 'alert'],
        },
        DETAIL_VIEW: {
          HEADER_LIST: [
            'minTime',
            'maxTime',
            'avgTime',
            'packetLoss',
            'status',
            'createdAt',
          ],
          HEADER_LABEL: {
            minTime: 'MinTime',
            maxTime: 'MaxTime',
            avgTime: 'AverageTime',
            packetLoss: 'PacketsLoss',
            status: 'Status',
            createdAt: 'Created At',
          },
        },
      },
      SSL: {
        ADD_EDIT_SSL: [
          {
            fieldName: 'name',
            label: 'Name',
            type: 'input',
            placeholder: 'Enter a friendly name/alias',
            required: true,
          },
          {
            fieldName: 'url',
            label: 'URL/IP',
            type: 'input',
            placeholder: 'e.g. www.google.com or 192.168.1.1',
            required: true,
            pattern:
              '^(https?:\\/\\/)?((([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6})|((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(\\/.*)?$',
          },
          {
            fieldName: 'interval',
            label: 'Interval',
            type: 'select',
            required: true,
            options: [
              { value: 1, viewValue: '1 minute' },
              { value: 5, viewValue: '5 minutes' },
              { value: 10, viewValue: '10 minutes' },
              { value: 30, viewValue: '30 minutes' },
              { value: 60, viewValue: '1 hour' },
            ],
          },
        ],
        LIST_VIEW: {
          HEADER_LIST: [
            'status',
            'counter',
            'name',
            'url',
            'interval',
            'createdAt',
            'createdBy',
            'latestRecord',
            'enable',
            'options',
          ],
          HEADER_LABEL: {
            counter: 'ID',
            name: 'Name',
            url: 'Url',
            interval: 'Interval',
            createdAt: 'Created At',
            createdBy: 'Created By',
            latestRecord: 'Latest Value (Days Left)',
            status: 'Status',
            enable: 'Enable/Disable',
            options: 'Operation',
          },
          ACTION_OPTIONS: ['edit', 'view', 'delete', 'alert'],
        },
        DETAIL_VIEW: {
          HEADER_LIST: [
            'valid',
            'nvBefore',
            'nvAfter',
            'createdAt',
            'connectionTime',
            'daysRemaining',
          ],
          HEADER_LABEL: {
            valid: 'Valid',
            nvBefore: 'NotValidBefore',
            nvAfter: 'NotValidAfter',
            createdAt: 'Created At',
            connectionTime: 'Connection Time',
            daysRemaining: 'Days Left',
          },
        },
      },
      PORT: {
        ADD_EDIT_PORT: [
          {
            fieldName: 'name',
            label: 'Name',
            type: 'input',
            placeholder: 'Enter a friendly name/alias',
            required: true,
          },
          {
            fieldName: 'host',
            label: 'Host',
            type: 'input',
            placeholder: 'e.g. www.google.com or 192.168.1.1',
            required: true,
            pattern: '^((([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6})|((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(\\/.*)?$'
          },
          {
            fieldName: 'ports',
            label: 'Ports',
            type: 'select',
            required: true,
            isArray: true,
            options: [
              { value: 80, viewValue: 'Port 80' },
              { value: 443, viewValue: 'Port 443' },
              { value: 22, viewValue: 'Port 22' },
              { value: 8080, viewValue: 'Port 8080' },
              { value: 'custom', viewValue: 'Custom Port' },  // Custom Port Option
            ],
          },
          {
            fieldName: 'interval',
            label: 'Interval',
            type: 'select',
            required: true,
            options: [
              { value: 1, viewValue: '1 minute' },
              { value: 5, viewValue: '5 minutes' },
              { value: 10, viewValue: '10 minutes' },
              { value: 30, viewValue: '30 minutes' },
              { value: 60, viewValue: '1 hour' },
            ],
          },
        ],
        LIST_VIEW: {
          HEADER_LIST: [
            'status',
            'counter',
            'name',
            'url',
            'port',
            'interval',
            'createdAt',
            'createdBy',
            'latestOpen',
            'latestClose',
            'enable',
            'options',
          ],
          HEADER_LABEL: {
            counter: 'ID',
            name: 'Name',
            url: 'Url',
            port: 'Port',
            interval: 'Interval',
            createdAt: 'Created At',
            createdBy: 'Created By',
            latestOpen: 'Latest Open',
            latestClose: 'Latest Close',
            status: 'Status',
            enable: 'Enable/Disable',
            options: 'Operation',
          },
          ACTION_OPTIONS: ['edit', 'view', 'delete','alert'],
        },
        DETAIL_VIEW: {
          HEADER_LIST: ['Ports', 'createdAt', 'openPorts', 'closePorts'],
          HEADER_LABEL: {
            Ports: 'Ports',
            createdAt: 'Created At',
            openPorts: 'openPorts',
            closePorts: 'closePorts',
          },
        },
      },

      WEBSITE: {
        ADD_EDIT_WEBSITE: [
          {
            fieldName: 'name',
            label: 'Name',
            type: 'input',
            required: true,
            placeholder: 'Enter a friendly name/alias',
          },
          {
            fieldName: 'interval',
            label: 'Interval',
            type: 'select',
            required: true,
            options: [
              { value: 1, viewValue: '1 minute' },
              { value: 5, viewValue: '5 minutes' },
              { value: 10, viewValue: '10 minutes' },
              { value: 30, viewValue: '30 minutes' },
              { value: 60, viewValue: '1 hour' },
            ],
          },
          {
            fieldName: 'proxy',
            label: 'Proxy',
            placeholder: 'Any HTTP(s) proxy to be used while monitoring',
            type: 'input',
            required: false,
          },
          {
            fieldName: 'steps',
            label: 'Steps',
            type: 'select',
            isArray: true,
            required: false,
          },
        ],
        LIST_VIEW: {
          HEADER_LIST: [
            'status',
            'counter',
            'name',
            'interval',
            'createdAt',
            'createdBy',
            'enable',
            'options',
          ],
          HEADER_LABEL: {
            counter: 'ID',
            name: 'Name',
            interval: 'Interval',
            createdAt: 'Created At',
            createdBy: 'Created By',
            status: 'Status',
            enable: 'Enable/Disable',
            options: 'Operation',
          },
          ACTION_OPTIONS: ['edit', 'view', 'delete','alert'],
        },
        DETAIL_VIEW: {
          HEADER_LIST: ['index', 'createdAt', 'steps'],
          HEADER_LABEL: {
            index : 'Validation',
            recordId: 'Record Id',
            createdAt: 'Created At',
            steps: 'Steps',
            // required_code: 'Required Code',
            // actual_code: 'Actual Code',
          },
        },
      },
      FILTER: {
        counter: {
          name: 'counter',
          type: 'text',
          label: 'ID',
          placeholder: ' ID',
          errorMessage: 'ID not provided!',
          required: true,
          show: true,
        },
        name: {
          name: 'name',
          type: 'text',
          label: 'Name',
          placeholder: 'Record Name',
          errorMessage: 'Record Name not provided!',
          required: true,
          show: true,
        },
        status: {
          name: 'status',
          type: 'dropdown',
          label: 'Status',
          placeholder: 'Status',
          dropdown: [
            { type: true, name: 'Active' },
            { type: false, name: 'Inactive' },
          ],
          errorMessage: 'Status not provided!',
          required: true,
          show: true,
        },
        createdBy: {
          name: 'createdBy',
          type: 'search',
          label: 'Created By',
          placeholder: 'Created By',
          errorMessage: 'Created By not provided!',
          required: true,
          addButton: true,
          selectButton: true,
          show: true,
        },
        createdById: { name: 'createdById', type: 'id', label: 'Created By Id', placeholder: 'createdById', errorMessage: 'Created By not provided!', required: false, show: true },

      },
    },
    ALERTING: {
      ALERT: {
        ADD_EDIT_ALERT: [
          {
            fieldName: 'name',
            label: 'Name/Alias',
            type: 'input',
            placeholder: 'Enter friendly Name',
            required: true,
          },
          {
            fieldName: 'status',
            label: 'Status',
            type: 'select',
            required: true,
            options: [
              { value: 'true', viewValue: 'Enabled' },
              { value: 'false', viewValue: 'Disabled' },
            ],
          },
          {
            fieldName: 'monitoringtype',
            label: 'Monitoring Type',
            type: 'select',
            required: true,
            options: [
              { value: 'list-port', viewValue: 'Active Port' },
              { value: 'list-ping', viewValue: 'Active Ping' },
              { value: 'list-ssl', viewValue: 'Active SSL' },
              {
                value: 'list-web-monitoring',
                viewValue: 'Active Web-Monitoring',
              },
            ],
          },
        ],
        LIST_VIEW: {
          HEADER_LIST: [
            'status',
            'name',
            'createdAt',
            'createdBy',
            'notifySources',
            'monitoringtype',
            'enable',
            'options',
          ],
          HEADER_LABEL: {
            name: 'Name',
            createdAt: 'Created At',
            createdBy: 'Created By',
            notifySources: 'NotifyAt',
            monitoringtype: 'Monitoring Type',
            status: 'Status',
            enable: 'Enable/Disable',
            options: 'Operation',
          },
          ACTION_OPTIONS: ['edit', 'view', 'delete'],
        },
      },
      FILTER: {
        counter: {
          name: 'counter',
          type: 'text',
          label: 'ID',
          placeholder: ' ID',
          errorMessage: 'ID not provided!',
          required: true,
          show: true,
        },
        name: {
          name: 'name',
          type: 'text',
          label: 'Name',
          placeholder: 'Alert Name',
          errorMessage: 'Alert Name not provided!',
          required: true,
          show: true,
        },
        status: {
          name: 'status',
          type: 'dropdown',
          label: 'Status',
          placeholder: 'Status',
          dropdown: [
            { type: true, name: 'Active' },
            { type: false, name: 'Inactive' },
          ],
          errorMessage: 'Status not provided!',
          required: true,
          show: true,
        },
        createdBy: {
          name: 'createdBy',
          type: 'search',
          label: 'Created By',
          placeholder: 'Created By',
          errorMessage: 'Created By not provided!',
          required: true,
          addButton: true,
          selectButton: true,
          show: true,
        },
        createdById: { name: 'createdById', type: 'id', label: 'Created By Id', placeholder: 'createdById', errorMessage: 'Created By not provided!', required: false, show: true },


      },
      MODAL_SELECT_VIEW: {
        PING: {
          HEADER_LIST: ['name', 'url', 'status' ],
          HEADER_LABEL: { 'name': 'Name', 'url': 'Url', 'status': 'Status' },
        },
        PORT: {
          HEADER_LIST: ['name', 'url', 'port', 'status', ],
          HEADER_LABEL: { 'name': 'Name', 'url': 'Url', 'port': 'Port', 'status': 'Status' },
        },
        SSL: {
          HEADER_LIST: ['name', 'url', 'status'],
          HEADER_LABEL: { 'name': 'Name', 'url': 'Url', 'status': 'Status'},
        },
        WEBSITE: {
          HEADER_LIST: ['name', 'url', 'proxy', 'status'],
          HEADER_LABEL: { 'name': 'Name', 'url': 'Url', 'proxy': 'Proxy', 'status': 'Status'},
        },
      }

    },
    USER_MANAGEMENT: {
      USERS: {
        LIST_VIEW: {
          HEADER_LIST: [
            'status',
            'name',
            'type',
            'email',
            'mobile',
            'modifiedAt',
            'enable',
            'options',
          ],
          HEADER_LABEL: {
            name: 'Name',
            email: 'Email',
            mobile: 'Mobile',
            options: 'Operation',
            type: 'Type',
            status: 'Status',
            modifiedAt: 'Modified Date ',
            enable: 'Enable/Disable',
          },
          ACTION_OPTIONS: ['edit', 'delete'],
        },
        FILTER: {
          name: {
            name: 'name',
            type: 'text',
            label: 'Name',
            placeholder: 'Full Name',
            errorMessage: 'Name not provided!',
            required: true,
            tooltip: false,
            tooltipMessage: '',
            show: true,
          },
          type: {
            name: 'type',
            type: 'dropdown',
            label: 'Type',
            placeholder: 'User or Admin?',
            dropdown: [
              { type: '0', name: 'User' },
              { type: '1', name: 'Admin' },
            ],
            errorMessage: 'Type not provided!',
            required: true,
            show: true,
          },
          email: {
            name: 'email',
            type: 'email',
            label: 'Email',
            placeholder: 'Email',
            errorMessage: 'Email not provided!',
            required: true,
            show: true,
          },
          mobile: {
            name: 'mobile',
            label: 'Mobile',
            type: 'number',
            placeholder: 'Mobile Number',
            errorMessage: 'Mobile Number not provided!',
            required: true,
            regex: '^[1-9][0-9]{9}$',
            show: true,
          },
        },
        DETAIL_VIEW: {
          FIELDS: [
            'name',
            'type',
            'email',
            'mobile',
            'company',
            'job_title',
            'department',
            'status',
            'createdDate',
            'createdBy',
            'modifiedDate',
            'modifiedBy',
          ],
          FIELDS_LABEL: {
            name: 'Name',
            type: 'Type',
            email: 'Email',
            mobile: 'Mobile',
            company: 'Company',
            job_title: 'Job Title',
            department: 'Department',
            status: 'Status',
            createdDate: 'Created Date',
            createdBy: 'Created By',
            modifiedDate: 'Modified Date',
            modifiedBy: 'Modified By',
          },
          ACTION_OPTIONS: ['edit', 'changeLog'],
        },
        SELECT_VIEW: {
          HEADER_LIST: ['name', 'type', 'status', 'action'],
          HEADER_LABEL: {
            name: 'Name',
            email: 'Email',
            mobile: 'Mobile',
            action: 'Operation',
            type: 'Type',
            company: 'Company',
            job_title: 'Job Title',
            department: 'Department',
            status: 'Status',
          },
          SELECT_VIEW_FILTER: {
            name: {
              name: 'name',
              type: 'text',
              label: 'Name',
              placeholder: 'Name',
              errorMessage: 'Name not provided!',
              show: true,
            },
            type: {
              name: 'type',
              type: 'select',
              label: 'Type',
              placeholder: 'User or Admin?',
              dropdown: [
                { type: '0', name: 'User' },
                { type: '1', name: 'Admin' },
              ],
              errorMessage: 'Type not provided!',
              required: true,
              show: true,
            },
          },
          MULTI_SELECT_VIEW_FILTER: {
            name: {
              name: 'name',
              type: 'text',
              label: 'Name',
              placeholder: 'Name',
              errorMessage: 'Name not provided!',
              show: true,
            },
            email: {
              name: 'email',
              type: 'email',
              label: 'Email',
              placeholder: 'Email',
              errorMessage: 'Email not provided!',
              required: true,
              show: true,
            },
            mobile: {
              name: 'mobile',
              label: 'Mobile',
              type: 'number',
              placeholder: 'Mobile Number',
              errorMessage: 'Mobile Number not provided!',
              required: true,
              regex: '^[1-9][0-9]{9}$',
              show: true,
            },
          },
          MULTI_HEADER_LIST: ['name', 'email', 'mobile', 'action'],
          MULTI_HEADER_LABEL: {
            name: 'Name',
            email: 'Email',
            mobile: 'Mobile',
            action: 'Operation',
            type: 'Type',
            company: 'Company',
            job_title: 'Job Title',
            department: 'Department',
            status: 'Status',
          },
        },
        MODAL_VIEW: {
          HEADER_LIST: ['name', 'type', 'status', 'deleted'],
          HEADER_LABEL: {
            name: 'Name',
            type: 'Type',
            status: 'Status',
            deleted: 'Deleted',
          },
        },
      },
    },
  },
};
